#pragma once

enum VARIANT_TYPE
{
	VARIANT_TYPE_NONE		,
	VARIANT_TYPE_BOOL		,
	VARIANT_TYPE_BYTE		,
	VARIANT_TYPE_CHAR		,
	VARIANT_TYPE_WCHAR		,
	VARIANT_TYPE_WORD		,
	VARIANT_TYPE_DWORD		,
	VARIANT_TYPE_SHORT		,
	VARIANT_TYPE_UINT		,
	VARIANT_TYPE_UINT32		,
	VARIANT_TYPE_UINT64		,
	VARIANT_TYPE_INT		,
	VARIANT_TYPE_INT32		,
	VARIANT_TYPE_INT64		,
	VARIANT_TYPE_FLOAT		,
	VARIANT_TYPE_DOUBLE		,
	VARIANT_TYPE_STRING		,
	VARIANT_TYPE_GUID		,
	VARIANT_TYPE_RECT		,
	VARIANT_TYPE_POINT		,
	VARIANT_TYPE_SIZE		,
	VARIANT_TYPE_OBJECT		,
} ;